---
# Claude Code PM Update Configuration
version: 1.0
upstream: https://github.com/kwai-egg/ccpm.git
branch: main

# Files and directories to preserve during updates (project-specific data)
preserve:
  - ".claude/epics/"           # PM workspace with project epics
  - ".claude/prds/"            # Product Requirements Documents
  - ".claude/context/"         # Project context documentation
  - ".claude/CLAUDE.md"        # Project-specific Claude instructions
  - ".claude/**/*.local.*"     # Any .local files (settings, configs)
  - ".claude/settings.json"    # Local settings
  - ".claude/config.yaml"      # Local configuration

# Files and directories to update from upstream (system components)
update:
  - ".claude/agents/"          # AI agent definitions
  - ".claude/commands/"        # Command specifications and implementations
  - ".claude/rules/"           # System operation rules and patterns
  - ".claude/scripts/"         # Automation and utility scripts
  - ".claude/templates/"       # Content templates and patterns
  - ".claude/VERSION"          # Version tracking
  - ".claude/CHANGELOG.md"     # System changelog

# Backup configuration
backup:
  enabled: true
  keep_backups: 5              # Number of file backups to retain
  backup_location: ".ccpm-backups/"

# Update behavior
update_behavior:
  check_uncommitted: false     # Optional warning for git changes
  create_backup: true          # Always create backup before update
  validate_after: true         # Run validation after update
  auto_cleanup: false          # Don't auto-delete backup directories

# Validation settings
validation:
  check_commands: true         # Verify command files are valid
  check_structure: true        # Verify directory structure
  check_dependencies: true     # Verify required tools are available
  check_files: true            # Verify critical files exist after update

# Memory Management Settings
memory_management:
  enabled: true
  max_concurrent_agents: 8     # Default maximum concurrent agents
  memory_per_agent_gb: 8       # Memory allocation per agent in GB
  total_memory_limit_gb: 96    # Total system memory available
  coordinator_memory_gb: 16    # Memory for coordinator process
  monitoring_enabled: true     # Enable memory monitoring
  cleanup_timeout: 30          # Timeout for agent cleanup in seconds
  retry_on_memory_limit: true  # Retry failed streams due to memory
  
# Node.js Environment Settings
node_options:
  coordinator_heap_size: 16384      # --max-old-space-size for coordinator
  agent_heap_size: 8192            # --max-old-space-size for agents
  gc_exposure: true                # --expose-gc for manual garbage collection
  optimize_for_size: true          # --optimize_for_size for memory efficiency
